#!/bin/bash

# for n in E2 A2 D3 G3 B3 E4; do
# play -n synth 4 pluck $n ; done
# exit

SRATE="192000"

rec -c 2 -b 32 -r $SRATE -L -e signed -t wavpcm rec.wav trim 0 00:15 &

sleep 1

sox -c 2 -b 32 -r $SRATE -L -e signed -n -t wavpcm - synth 10 sine 0+20000 \
| aplay --disable-resample --disable-channels --disable-format --disable-softvol \
        --test-nowait -V mono -D hw:CARD=SB,DEV=0 -q -t wav -
        
sox -c 2 -b 32 -r $SRATE -L -e signed -n -t wavpcm - synth 0.5 sine 1000 \
| aplay --disable-resample --disable-channels --disable-format --disable-softvol \
        --test-nowait -V mono -D hw:CARD=SB,DEV=0 -q -t wav -

sox -c 2 -b 32 -r $SRATE -L -e signed -n -t wavpcm - synth 0.5 sine 700 synth 0.5 sine mix 8000 \
| aplay --disable-resample --disable-channels --disable-format --disable-softvol \
        --test-nowait -V mono -D hw:CARD=SB,DEV=0 -q -t wav -

sleep 5

sox -V rec.wav -n remix 1 spectrogram -w Kaiser -x5000 -y1200 -z120 -W 10 -h -o spectrum.png ; eog spectrum.png
# sox -V rec.wav -n spectrogram -w Kaiser -x5000 -y1200 -z120 -W 10 -h -o spectrum.png ; eog spectrum.png

