#!/bin/bash
#

# astyle -A1 -t $1.c

gcc -std=gnu99 -pedantic -O3 -mtune=native -march=native -ffast-math -fomit-frame-pointer -fverbose-asm -S $1.c
gcc -std=gnu99 -pedantic -O3 -mtune=native -march=native -ffast-math -fomit-frame-pointer -Wall -c $1.c

#gcc $1.o -lasound -lfftw3 -lm
gcc $1.o `pkg-config --cflags --libs alsa fftw3` -lm

if [ $? -ne 0 ]; then
  echo "Errors linking and loading "
  exit
fi

rm $1.o
mv a.out $1
strip $1


